#!/bin/bash
echo "=========================================="
echo "Configuration GitHub pour Epaiement.ma"
echo "=========================================="
echo ""
echo "Étape 1: Créez un repository sur GitHub"
echo "  → Allez sur: https://github.com/new"
echo "  → Nom suggéré: epaiement-ma"
echo "  → Ne PAS initialiser avec README (on a déjà le code)"
echo "  → Cliquez 'Create repository'"
echo ""
echo "Étape 2: Après création, copiez l'URL du repo"
echo "  → Format: https://github.com/VOTRE_USERNAME/epaiement-ma.git"
echo ""
echo "Étape 3: Exécutez ces commandes:"
echo ""
echo "  git remote add origin https://github.com/VOTRE_USERNAME/epaiement-ma.git"
echo "  git branch -M main"
echo "  git push -u origin main"
echo ""
echo "Étape 4: Connectez à Vercel"
echo "  → Allez sur: https://vercel.com/dashboard"
echo "  → Import Project → Import Git Repository"
echo "  → Sélectionnez votre repo 'epaiement-ma'"
echo ""
echo "=========================================="
